spring.application.name=order-matching-engine
server.port=8005

spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
spring.datasource.username=myuser
spring.datasource.password=mypassword
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.security.user.name=ome
spring.security.user.password=123
# JWT configuration
jwt.secret=superSecretKey@13752023superSecretKey@1375
# 1hour lifeSpan
jwt.token.lifespan=3600000
